apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: threat-app-ingress
  annotations:
    cert-manager.io/cluster-issuer: "issuer"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - threat-app.eks.abdikarim-tech.com
      secretName: threat-app-tls
  rules:
    - host: threat-app.eks.abdikarim-tech.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: threat-app-service
                port:
                  number: 3000