name: build and push to AWS ECR
on:
  push:
    branches: [main]
    paths:
      - 'apps/**'
      - 'docker/**'
      - '.github/workflows/build-and-push.yaml'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      security-events: write
    
    env:
      AWS_REGION: eu-north-1
      ECR_REGISTRY: eks

    steps:
      - name: checkout code
        uses: actions/checkout@v3
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_BUILD_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          region: ${{ env.AWS_REGION }}
        
      - name: set image tag with SHA
        run: | 
           IMAGE_TAG=$(echo "${{ github.sha }}" | cut -c1-7)
           echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
        
      - name: build docker image
        run: |
            docker build \
            -f docker/dockerfile \
            -t ${{ steps.login-ecr.outputs.registry }}/eks:${{ env.IMAGE_TAG }} \
            .
      
      - name: run trivy vulnerabillity scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ steps.login-ecr.outputs.registry }}/eks:${{ env.IMAGE_TAG }}
          format: sarif
          output: trivy-build-result.sarif
          exit-code: '1'
          severity: 'CRITICAL,HIGH'
      
      - name: Upload Trivy scan results to GitHub Security
        if: failure()
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: trivy-build-result.sarif
      
      - name: push image to AWS ECR
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/eks:${{ env.IMAGE_TAG }}

      